image: ubuntu:latest

variables:
  CARGO_HOME: /.cargo
  CARGO_BIN: $CARGO_HOME/bin

stages:
  - build
  - test
  - deploy

before_script:
  - apt update -y -qq && apt -y -qq install curl build-essential libssl-dev pkg-config
  - "[ ! -d $CARGO_HOME ] && curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path"

.build_template: &build_def
  stage: build
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    when: on_success
    paths:
      - build

debug_build:
  <<: *build_def
  script:
    - $CARGO_BIN/cargo build
    - pwd
    - ls -al
    - mv target/debug/ ./build
  environment:
    name: debug

release_build:
  <<: *build_def
  only:
    - tags
  script:
    - $CARGO_BIN/cargo build --release
    - mv target/release/ ./build
  environment:
    name: release

.test_template: &test_def
  stage: test

debug_test:
  <<: *test_def
  script:
    - $CARGO_BIN/cargo test
  environment:
    name: debug

release_test:
  <<: *test_def
  script:
    - $CARGO_BIN/cargo test --release
  environment:
    name: release

# Host documentation on gitlab pages
pages:
  stage: deploy
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    when: on_success
    paths:
      - public/
  script:
    - $CARGO_BIN/cargo doc
    - mv target/doc/ public/
  only:
    - master
