[package]
name = "transaction_processor"
version = "0.1.0"
authors = ["\"Spencer Ferris\" <sferris37@gmail.com>"]

[dependencies]
chrono = "0.4"
csv = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
argparse = "0.2"
itertools = "0.7"
fantoccini = "0.9"
futures = "0.1"
tokio-core = "0.1"
regex = "1.0"
url = "1.7"
webdriver = "0.34"
rustc-serialize = "0.3"
tempfile = "3.0"
text_io = "0.1"
rpassword = "2.0"
